# https://aka.ms/yaml

trigger:
  - master

variables:
    regression: 1

jobs:
  - job: build_ubuntu_gpu
    displayName: Ubuntu MMseqs2 GPU
    pool:
      vmImage: 'Ubuntu-20.04'
    timeoutInMinutes: 120
    steps:
      - checkout: self
        submodules: false
      - task: Docker@2
        displayName: Build Docker Image
        inputs:
          command: build
          dockerfile: '.github/workflows/Dockerfile.GPU-manylinux2014'
          tags: |
            manylinux-latest:latest
          buildContext: '$(Build.SourcesDirectory)'
      - script: |
          mkdir -p ${BUILD_SOURCESDIRECTORY}/output
          docker run --rm \
            -v ${BUILD_SOURCESDIRECTORY}/output:/output \
            manylinux-latest:latest \
            /bin/bash -c "cp /work/build/src/mmseqs /output/"
        displayName: Run Docker Container and Copy Binary
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: $(Build.SourcesDirectory)/output/mmseqs
          artifactName: mmseqs-linux-gpu